### ISSUE TITLE
send_file() got an unexpected keyword argument 'max_age'

### ISSUE THREAD

**Issue by ALEXDINO7** [Dilshan-H/Oblivion-Inverse#1]
please how I can solve this 

send_file() got an unexpected keyword argument 'max_age'

**Comment by Dilshan-H** [comment]
According to the Flask Documentation `max_age` replaces the `cache_timeout` parameter version 2.0.0 onward. So, we can remove the `cache_timeout` parameter then. Hope this will fix your issue too @ALEXDINO7
