### ISSUE TITLE
Only allows mail upto a certain length

### ISSUE THREAD

**Issue by Jaskaran2** [Dilshan-H/Oblivion-Inverse#12]
**Describe the bug**
While entering a mail if the mail is longer than a certain length it gets blocked. The max length being 25

**To Reproduce**
1. Go to index page
2. Enter a mail with more than 25 characters

**Comment by Dilshan-H** [comment]
The 25 character limit was introduced as it directly appears inside the cards (track list dashboard) and longer text may negatively effect the appearance of UI (like overflow in cards)
I guess it would be better if we can increase this character limit upto some count like 50 or 100 and handle the overflow issue in UI 🤔

For instance;

`This is a sample text for title of an email`

Will be shown as:

`This is a sample text ... `

It's basically shortening the entire title in cards.

**Comment by Jaskaran2** [comment]
Yes I believe limit of 50 should be more than enough for it.

**Comment by Dilshan-H** [comment]
> Yes I believe limit of 50 should be more than enough for it.

Sure, and implementing the title shortening on UI will fix this issue.
