### ISSUE TITLE
Add Darkmode to UI

### ISSUE THREAD

**Issue by Dilshan-H** [Dilshan-H/Oblivion-Inverse#5]
It's nice to have a way to switch between light and dark modes inside UI!

**Comment by heza-ru** [comment]
I added some script for dark mode please review.

**Comment by tejask1730** [comment]
@Dilshan-H i would like to work on it , assign it to me

**Comment by krishnabiradar310802** [comment]
@Dilshan-H Can i work on this issue?

**Comment by Dilshan-H** [comment]
#6

**Comment by Dilshan-H** [comment]
@tejask1730 @krishnabiradar310802 Thanks for your interest towards this project 🤗
Since there are PRs are already avaliable for this issue, could you please look into new features or bugs?
